version: '3'

services:
  web:
    build: ./locallibrary-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./locallibrary-app/:/usr/src/locallibrary/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
